name: Greenway1
favicon: null
layout_spectrum: 0.9833
typography_spectrum: 0.57095
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#052705'
    - '#EAE0D6'
    - '#5D4B38'
    - '#64B455'
    - '#D7D865'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
