analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4634801
  brandStrength: 1
  lightness: 0.5429646
  brandColors:
    - '#052705'
    - '#EAE0D6'
    - '#5D4B38'
    - '#64B455'
    - '#D7D865'
  rhythmicContrast: 0.3925886
typography_spectrum: 0.8560843190643936
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
name: Greenway1
