favicon: null
name: Greenway1
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.9375
  rhythmicContrast: 0.5
  brandColors:
    - '#052705'
    - '#EAE0D6'
    - '#5D4B38'
    - '#64B455'
    - '#D7D865'
  lightness: 0.8125
typography_spectrum: 0.556928
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9833
analytics:
  twitter: null
  google: null
  facebook: null
